// Code generated by SQLBoiler 4.14.0 (https://github.com/volatiletech/sqlboiler). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package models

import (
	"bytes"
	"context"
	"reflect"
	"testing"

	"github.com/volatiletech/randomize"
	"github.com/volatiletech/sqlboiler/v4/boil"
	"github.com/volatiletech/sqlboiler/v4/queries"
	"github.com/volatiletech/strmangle"
)

var (
	// Relationships sometimes use the reflection helper queries.Equal/queries.Assign
	// so force a package dependency in case they don't.
	_ = queries.Equal
)

func testTransactionCategories(t *testing.T) {
	t.Parallel()

	query := TransactionCategories()

	if query.Query == nil {
		t.Error("expected a query, got nothing")
	}
}

func testTransactionCategoriesDelete(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &TransactionCategory{}
	if err = randomize.Struct(seed, o, transactionCategoryDBTypes, true, transactionCategoryColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize TransactionCategory struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	if rowsAff, err := o.Delete(ctx, tx); err != nil {
		t.Error(err)
	} else if rowsAff != 1 {
		t.Error("should only have deleted one row, but affected:", rowsAff)
	}

	count, err := TransactionCategories().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 0 {
		t.Error("want zero records, got:", count)
	}
}

func testTransactionCategoriesQueryDeleteAll(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &TransactionCategory{}
	if err = randomize.Struct(seed, o, transactionCategoryDBTypes, true, transactionCategoryColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize TransactionCategory struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	if rowsAff, err := TransactionCategories().DeleteAll(ctx, tx); err != nil {
		t.Error(err)
	} else if rowsAff != 1 {
		t.Error("should only have deleted one row, but affected:", rowsAff)
	}

	count, err := TransactionCategories().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 0 {
		t.Error("want zero records, got:", count)
	}
}

func testTransactionCategoriesSliceDeleteAll(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &TransactionCategory{}
	if err = randomize.Struct(seed, o, transactionCategoryDBTypes, true, transactionCategoryColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize TransactionCategory struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	slice := TransactionCategorySlice{o}

	if rowsAff, err := slice.DeleteAll(ctx, tx); err != nil {
		t.Error(err)
	} else if rowsAff != 1 {
		t.Error("should only have deleted one row, but affected:", rowsAff)
	}

	count, err := TransactionCategories().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 0 {
		t.Error("want zero records, got:", count)
	}
}

func testTransactionCategoriesExists(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &TransactionCategory{}
	if err = randomize.Struct(seed, o, transactionCategoryDBTypes, true, transactionCategoryColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize TransactionCategory struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	e, err := TransactionCategoryExists(ctx, tx, o.ID)
	if err != nil {
		t.Errorf("Unable to check if TransactionCategory exists: %s", err)
	}
	if !e {
		t.Errorf("Expected TransactionCategoryExists to return true, but got false.")
	}
}

func testTransactionCategoriesFind(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &TransactionCategory{}
	if err = randomize.Struct(seed, o, transactionCategoryDBTypes, true, transactionCategoryColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize TransactionCategory struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	transactionCategoryFound, err := FindTransactionCategory(ctx, tx, o.ID)
	if err != nil {
		t.Error(err)
	}

	if transactionCategoryFound == nil {
		t.Error("want a record, got nil")
	}
}

func testTransactionCategoriesBind(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &TransactionCategory{}
	if err = randomize.Struct(seed, o, transactionCategoryDBTypes, true, transactionCategoryColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize TransactionCategory struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	if err = TransactionCategories().Bind(ctx, tx, o); err != nil {
		t.Error(err)
	}
}

func testTransactionCategoriesOne(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &TransactionCategory{}
	if err = randomize.Struct(seed, o, transactionCategoryDBTypes, true, transactionCategoryColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize TransactionCategory struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	if x, err := TransactionCategories().One(ctx, tx); err != nil {
		t.Error(err)
	} else if x == nil {
		t.Error("expected to get a non nil record")
	}
}

func testTransactionCategoriesAll(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	transactionCategoryOne := &TransactionCategory{}
	transactionCategoryTwo := &TransactionCategory{}
	if err = randomize.Struct(seed, transactionCategoryOne, transactionCategoryDBTypes, false, transactionCategoryColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize TransactionCategory struct: %s", err)
	}
	if err = randomize.Struct(seed, transactionCategoryTwo, transactionCategoryDBTypes, false, transactionCategoryColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize TransactionCategory struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = transactionCategoryOne.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}
	if err = transactionCategoryTwo.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	slice, err := TransactionCategories().All(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if len(slice) != 2 {
		t.Error("want 2 records, got:", len(slice))
	}
}

func testTransactionCategoriesCount(t *testing.T) {
	t.Parallel()

	var err error
	seed := randomize.NewSeed()
	transactionCategoryOne := &TransactionCategory{}
	transactionCategoryTwo := &TransactionCategory{}
	if err = randomize.Struct(seed, transactionCategoryOne, transactionCategoryDBTypes, false, transactionCategoryColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize TransactionCategory struct: %s", err)
	}
	if err = randomize.Struct(seed, transactionCategoryTwo, transactionCategoryDBTypes, false, transactionCategoryColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize TransactionCategory struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = transactionCategoryOne.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}
	if err = transactionCategoryTwo.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	count, err := TransactionCategories().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 2 {
		t.Error("want 2 records, got:", count)
	}
}

func transactionCategoryBeforeInsertHook(ctx context.Context, e boil.ContextExecutor, o *TransactionCategory) error {
	*o = TransactionCategory{}
	return nil
}

func transactionCategoryAfterInsertHook(ctx context.Context, e boil.ContextExecutor, o *TransactionCategory) error {
	*o = TransactionCategory{}
	return nil
}

func transactionCategoryAfterSelectHook(ctx context.Context, e boil.ContextExecutor, o *TransactionCategory) error {
	*o = TransactionCategory{}
	return nil
}

func transactionCategoryBeforeUpdateHook(ctx context.Context, e boil.ContextExecutor, o *TransactionCategory) error {
	*o = TransactionCategory{}
	return nil
}

func transactionCategoryAfterUpdateHook(ctx context.Context, e boil.ContextExecutor, o *TransactionCategory) error {
	*o = TransactionCategory{}
	return nil
}

func transactionCategoryBeforeDeleteHook(ctx context.Context, e boil.ContextExecutor, o *TransactionCategory) error {
	*o = TransactionCategory{}
	return nil
}

func transactionCategoryAfterDeleteHook(ctx context.Context, e boil.ContextExecutor, o *TransactionCategory) error {
	*o = TransactionCategory{}
	return nil
}

func transactionCategoryBeforeUpsertHook(ctx context.Context, e boil.ContextExecutor, o *TransactionCategory) error {
	*o = TransactionCategory{}
	return nil
}

func transactionCategoryAfterUpsertHook(ctx context.Context, e boil.ContextExecutor, o *TransactionCategory) error {
	*o = TransactionCategory{}
	return nil
}

func testTransactionCategoriesHooks(t *testing.T) {
	t.Parallel()

	var err error

	ctx := context.Background()
	empty := &TransactionCategory{}
	o := &TransactionCategory{}

	seed := randomize.NewSeed()
	if err = randomize.Struct(seed, o, transactionCategoryDBTypes, false); err != nil {
		t.Errorf("Unable to randomize TransactionCategory object: %s", err)
	}

	AddTransactionCategoryHook(boil.BeforeInsertHook, transactionCategoryBeforeInsertHook)
	if err = o.doBeforeInsertHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doBeforeInsertHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected BeforeInsertHook function to empty object, but got: %#v", o)
	}
	transactionCategoryBeforeInsertHooks = []TransactionCategoryHook{}

	AddTransactionCategoryHook(boil.AfterInsertHook, transactionCategoryAfterInsertHook)
	if err = o.doAfterInsertHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doAfterInsertHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected AfterInsertHook function to empty object, but got: %#v", o)
	}
	transactionCategoryAfterInsertHooks = []TransactionCategoryHook{}

	AddTransactionCategoryHook(boil.AfterSelectHook, transactionCategoryAfterSelectHook)
	if err = o.doAfterSelectHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doAfterSelectHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected AfterSelectHook function to empty object, but got: %#v", o)
	}
	transactionCategoryAfterSelectHooks = []TransactionCategoryHook{}

	AddTransactionCategoryHook(boil.BeforeUpdateHook, transactionCategoryBeforeUpdateHook)
	if err = o.doBeforeUpdateHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doBeforeUpdateHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected BeforeUpdateHook function to empty object, but got: %#v", o)
	}
	transactionCategoryBeforeUpdateHooks = []TransactionCategoryHook{}

	AddTransactionCategoryHook(boil.AfterUpdateHook, transactionCategoryAfterUpdateHook)
	if err = o.doAfterUpdateHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doAfterUpdateHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected AfterUpdateHook function to empty object, but got: %#v", o)
	}
	transactionCategoryAfterUpdateHooks = []TransactionCategoryHook{}

	AddTransactionCategoryHook(boil.BeforeDeleteHook, transactionCategoryBeforeDeleteHook)
	if err = o.doBeforeDeleteHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doBeforeDeleteHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected BeforeDeleteHook function to empty object, but got: %#v", o)
	}
	transactionCategoryBeforeDeleteHooks = []TransactionCategoryHook{}

	AddTransactionCategoryHook(boil.AfterDeleteHook, transactionCategoryAfterDeleteHook)
	if err = o.doAfterDeleteHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doAfterDeleteHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected AfterDeleteHook function to empty object, but got: %#v", o)
	}
	transactionCategoryAfterDeleteHooks = []TransactionCategoryHook{}

	AddTransactionCategoryHook(boil.BeforeUpsertHook, transactionCategoryBeforeUpsertHook)
	if err = o.doBeforeUpsertHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doBeforeUpsertHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected BeforeUpsertHook function to empty object, but got: %#v", o)
	}
	transactionCategoryBeforeUpsertHooks = []TransactionCategoryHook{}

	AddTransactionCategoryHook(boil.AfterUpsertHook, transactionCategoryAfterUpsertHook)
	if err = o.doAfterUpsertHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doAfterUpsertHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected AfterUpsertHook function to empty object, but got: %#v", o)
	}
	transactionCategoryAfterUpsertHooks = []TransactionCategoryHook{}
}

func testTransactionCategoriesInsert(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &TransactionCategory{}
	if err = randomize.Struct(seed, o, transactionCategoryDBTypes, true, transactionCategoryColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize TransactionCategory struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	count, err := TransactionCategories().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 1 {
		t.Error("want one record, got:", count)
	}
}

func testTransactionCategoriesInsertWhitelist(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &TransactionCategory{}
	if err = randomize.Struct(seed, o, transactionCategoryDBTypes, true); err != nil {
		t.Errorf("Unable to randomize TransactionCategory struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Whitelist(transactionCategoryColumnsWithoutDefault...)); err != nil {
		t.Error(err)
	}

	count, err := TransactionCategories().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 1 {
		t.Error("want one record, got:", count)
	}
}

func testTransactionCategoryToManyTransactions(t *testing.T) {
	var err error
	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()

	var a TransactionCategory
	var b, c Transaction

	seed := randomize.NewSeed()
	if err = randomize.Struct(seed, &a, transactionCategoryDBTypes, true, transactionCategoryColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize TransactionCategory struct: %s", err)
	}

	if err := a.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Fatal(err)
	}

	if err = randomize.Struct(seed, &b, transactionDBTypes, false, transactionColumnsWithDefault...); err != nil {
		t.Fatal(err)
	}
	if err = randomize.Struct(seed, &c, transactionDBTypes, false, transactionColumnsWithDefault...); err != nil {
		t.Fatal(err)
	}

	b.TransactionCategoryID = a.ID
	c.TransactionCategoryID = a.ID

	if err = b.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Fatal(err)
	}
	if err = c.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Fatal(err)
	}

	check, err := a.Transactions().All(ctx, tx)
	if err != nil {
		t.Fatal(err)
	}

	bFound, cFound := false, false
	for _, v := range check {
		if v.TransactionCategoryID == b.TransactionCategoryID {
			bFound = true
		}
		if v.TransactionCategoryID == c.TransactionCategoryID {
			cFound = true
		}
	}

	if !bFound {
		t.Error("expected to find b")
	}
	if !cFound {
		t.Error("expected to find c")
	}

	slice := TransactionCategorySlice{&a}
	if err = a.L.LoadTransactions(ctx, tx, false, (*[]*TransactionCategory)(&slice), nil); err != nil {
		t.Fatal(err)
	}
	if got := len(a.R.Transactions); got != 2 {
		t.Error("number of eager loaded records wrong, got:", got)
	}

	a.R.Transactions = nil
	if err = a.L.LoadTransactions(ctx, tx, true, &a, nil); err != nil {
		t.Fatal(err)
	}
	if got := len(a.R.Transactions); got != 2 {
		t.Error("number of eager loaded records wrong, got:", got)
	}

	if t.Failed() {
		t.Logf("%#v", check)
	}
}

func testTransactionCategoryToManyAddOpTransactions(t *testing.T) {
	var err error

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()

	var a TransactionCategory
	var b, c, d, e Transaction

	seed := randomize.NewSeed()
	if err = randomize.Struct(seed, &a, transactionCategoryDBTypes, false, strmangle.SetComplement(transactionCategoryPrimaryKeyColumns, transactionCategoryColumnsWithoutDefault)...); err != nil {
		t.Fatal(err)
	}
	foreigners := []*Transaction{&b, &c, &d, &e}
	for _, x := range foreigners {
		if err = randomize.Struct(seed, x, transactionDBTypes, false, strmangle.SetComplement(transactionPrimaryKeyColumns, transactionColumnsWithoutDefault)...); err != nil {
			t.Fatal(err)
		}
	}

	if err := a.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Fatal(err)
	}
	if err = b.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Fatal(err)
	}
	if err = c.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Fatal(err)
	}

	foreignersSplitByInsertion := [][]*Transaction{
		{&b, &c},
		{&d, &e},
	}

	for i, x := range foreignersSplitByInsertion {
		err = a.AddTransactions(ctx, tx, i != 0, x...)
		if err != nil {
			t.Fatal(err)
		}

		first := x[0]
		second := x[1]

		if a.ID != first.TransactionCategoryID {
			t.Error("foreign key was wrong value", a.ID, first.TransactionCategoryID)
		}
		if a.ID != second.TransactionCategoryID {
			t.Error("foreign key was wrong value", a.ID, second.TransactionCategoryID)
		}

		if first.R.TransactionCategory != &a {
			t.Error("relationship was not added properly to the foreign slice")
		}
		if second.R.TransactionCategory != &a {
			t.Error("relationship was not added properly to the foreign slice")
		}

		if a.R.Transactions[i*2] != first {
			t.Error("relationship struct slice not set to correct value")
		}
		if a.R.Transactions[i*2+1] != second {
			t.Error("relationship struct slice not set to correct value")
		}

		count, err := a.Transactions().Count(ctx, tx)
		if err != nil {
			t.Fatal(err)
		}
		if want := int64((i + 1) * 2); count != want {
			t.Error("want", want, "got", count)
		}
	}
}

func testTransactionCategoriesReload(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &TransactionCategory{}
	if err = randomize.Struct(seed, o, transactionCategoryDBTypes, true, transactionCategoryColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize TransactionCategory struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	if err = o.Reload(ctx, tx); err != nil {
		t.Error(err)
	}
}

func testTransactionCategoriesReloadAll(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &TransactionCategory{}
	if err = randomize.Struct(seed, o, transactionCategoryDBTypes, true, transactionCategoryColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize TransactionCategory struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	slice := TransactionCategorySlice{o}

	if err = slice.ReloadAll(ctx, tx); err != nil {
		t.Error(err)
	}
}

func testTransactionCategoriesSelect(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &TransactionCategory{}
	if err = randomize.Struct(seed, o, transactionCategoryDBTypes, true, transactionCategoryColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize TransactionCategory struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	slice, err := TransactionCategories().All(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if len(slice) != 1 {
		t.Error("want one record, got:", len(slice))
	}
}

var (
	transactionCategoryDBTypes = map[string]string{`ID`: `bigint`, `Name`: `character varying`, `DeletedAt`: `timestamp with time zone`, `UpdatedAt`: `timestamp with time zone`, `CreatedAt`: `timestamp with time zone`}
	_                          = bytes.MinRead
)

func testTransactionCategoriesUpdate(t *testing.T) {
	t.Parallel()

	if 0 == len(transactionCategoryPrimaryKeyColumns) {
		t.Skip("Skipping table with no primary key columns")
	}
	if len(transactionCategoryAllColumns) == len(transactionCategoryPrimaryKeyColumns) {
		t.Skip("Skipping table with only primary key columns")
	}

	seed := randomize.NewSeed()
	var err error
	o := &TransactionCategory{}
	if err = randomize.Struct(seed, o, transactionCategoryDBTypes, true, transactionCategoryColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize TransactionCategory struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	count, err := TransactionCategories().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 1 {
		t.Error("want one record, got:", count)
	}

	if err = randomize.Struct(seed, o, transactionCategoryDBTypes, true, transactionCategoryPrimaryKeyColumns...); err != nil {
		t.Errorf("Unable to randomize TransactionCategory struct: %s", err)
	}

	if rowsAff, err := o.Update(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	} else if rowsAff != 1 {
		t.Error("should only affect one row but affected", rowsAff)
	}
}

func testTransactionCategoriesSliceUpdateAll(t *testing.T) {
	t.Parallel()

	if len(transactionCategoryAllColumns) == len(transactionCategoryPrimaryKeyColumns) {
		t.Skip("Skipping table with only primary key columns")
	}

	seed := randomize.NewSeed()
	var err error
	o := &TransactionCategory{}
	if err = randomize.Struct(seed, o, transactionCategoryDBTypes, true, transactionCategoryColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize TransactionCategory struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	count, err := TransactionCategories().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 1 {
		t.Error("want one record, got:", count)
	}

	if err = randomize.Struct(seed, o, transactionCategoryDBTypes, true, transactionCategoryPrimaryKeyColumns...); err != nil {
		t.Errorf("Unable to randomize TransactionCategory struct: %s", err)
	}

	// Remove Primary keys and unique columns from what we plan to update
	var fields []string
	if strmangle.StringSliceMatch(transactionCategoryAllColumns, transactionCategoryPrimaryKeyColumns) {
		fields = transactionCategoryAllColumns
	} else {
		fields = strmangle.SetComplement(
			transactionCategoryAllColumns,
			transactionCategoryPrimaryKeyColumns,
		)
	}

	value := reflect.Indirect(reflect.ValueOf(o))
	typ := reflect.TypeOf(o).Elem()
	n := typ.NumField()

	updateMap := M{}
	for _, col := range fields {
		for i := 0; i < n; i++ {
			f := typ.Field(i)
			if f.Tag.Get("boil") == col {
				updateMap[col] = value.Field(i).Interface()
			}
		}
	}

	slice := TransactionCategorySlice{o}
	if rowsAff, err := slice.UpdateAll(ctx, tx, updateMap); err != nil {
		t.Error(err)
	} else if rowsAff != 1 {
		t.Error("wanted one record updated but got", rowsAff)
	}
}

func testTransactionCategoriesUpsert(t *testing.T) {
	t.Parallel()

	if len(transactionCategoryAllColumns) == len(transactionCategoryPrimaryKeyColumns) {
		t.Skip("Skipping table with only primary key columns")
	}

	seed := randomize.NewSeed()
	var err error
	// Attempt the INSERT side of an UPSERT
	o := TransactionCategory{}
	if err = randomize.Struct(seed, &o, transactionCategoryDBTypes, true); err != nil {
		t.Errorf("Unable to randomize TransactionCategory struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Upsert(ctx, tx, false, nil, boil.Infer(), boil.Infer()); err != nil {
		t.Errorf("Unable to upsert TransactionCategory: %s", err)
	}

	count, err := TransactionCategories().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}
	if count != 1 {
		t.Error("want one record, got:", count)
	}

	// Attempt the UPDATE side of an UPSERT
	if err = randomize.Struct(seed, &o, transactionCategoryDBTypes, false, transactionCategoryPrimaryKeyColumns...); err != nil {
		t.Errorf("Unable to randomize TransactionCategory struct: %s", err)
	}

	if err = o.Upsert(ctx, tx, true, nil, boil.Infer(), boil.Infer()); err != nil {
		t.Errorf("Unable to upsert TransactionCategory: %s", err)
	}

	count, err = TransactionCategories().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}
	if count != 1 {
		t.Error("want one record, got:", count)
	}
}
